-- Generated by matugen - do not edit manually
return {
  base00 = '#021433', -- background
  base01 = '#22263f', -- lighter bg (status bars, line number bg)
  base02 = '#41384b', -- selection bg
  base03 = '#604a57', -- comments
  base04 = '#7f5c63', -- dark fg (status bars)
  base05 = '#9e6e6f', -- default fg
  base06 = '#bd807b', -- light fg
  base07 = '#dc9187', -- bright fg
  base08 = '#2a8ab3', -- variables, diff deleted
  base09 = '#b5484f', -- integers, booleans, constants
  base0A = '#0c3c6f', -- classes, search highlight
  base0B = '#2d5988', -- strings
  base0C = '#dc9186', -- regex, escape chars
  base0D = '#79283f', -- functions, headings
  base0E = '#042147', -- keywords
  base0F = '#521b3d', -- deprecated
}
