#!/usr/bin/env bash
# Stow the dotfiles into $HOME.
#
# --no-folding : create real directories, symlink individual files only,
#                so runtime/generated files land next to the symlinks in
#                $HOME instead of inside this repo.
# --adopt      : if a real file already exists at a target path (e.g. an
#                app autogenerated a config), move it into the repo and
#                symlink it; the git restore below then puts the repo's
#                version back — the repo always wins.
set -euo pipefail
cd "$(dirname "$0")"

if [[ -n "$(git status --porcelain --untracked-files=no)" ]]; then
    echo "error: uncommitted changes to tracked files — commit or stash first." >&2
    echo "       (--adopt + git restore would discard them)" >&2
    exit 1
fi

stow --restow --no-folding --adopt --target="$HOME" .
git restore .
echo "stowed into $HOME (repo versions win)"
