#!/usr/bin/env bash
set -eu
FILE_PATH="${1}" # Full path of the highlighted file
WIDTH="${2}"     # Width of the preview pane (number of fitting characters)
HEIGHT="${3}"    # Height of the preview pane (number of fitting characters)
X="${4}"         # X coordinate of the preview pane
Y="${5}"         # Y coordinate of the preview pane

# If img run kitty, else bat
[[ "$(file -Lb --mime-type "$1")" =~ ^image ]] || bat --color always "$1"
kitty +kitten icat --stdin no --transfer-mode memory --place "${WIDTH}x${HEIGHT}@${X}x${Y}" "$1" </dev/null >/dev/tty
exit 1
