--  _   _                  _                 _
-- | | | |_   _ _ __  _ __| | __ _ _ __   __| |
-- | |_| | | | | '_ \| '__| |/ _` | '_ \ / _` |
-- |  _  | |_| | |_) | |  | | (_| | | | | (_| |
-- |_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_|
--        |___/|_|

---@module 'hl'

-- Colors are generated by matugen into ~/.config/hypr/colors.lua and pulled
-- in by conf/window.lua and conf/decoration.lua via require("colors").
-- Hyprland resolves this file's stow symlink into the repo, so the live
-- config dir must be on the module search path for colors.lua to be found.
package.path = os.getenv("HOME") .. "/.config/hypr/?.lua;" .. package.path

require("conf.monitor")
require("conf.cursor")
require("conf.keyboard")
require("conf.autostart")

require("conf.window")
require("conf.decoration")
require("conf.layout")
require("conf.misc")
require("conf.keybinding")
require("conf.windowrules")

require("conf.animation")

require("conf.custom")

-- Environment for xdg-desktop-portal-hyprland
hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
end)
