-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ----------------------------------------------------- 

-- Autostart

-- ----------------------------------------------------- 

-- Start waybar

-- Start hyprpaper

-- Load Dunst Notification Manager

-- Using hypridle to start hyprlock

-- Load cliphist history

-- Load onedrive

-- Moved to systemd

-- exec-once = uwsm app -- rclone --vfs-cache-mode writes mount oneDrive: onedrive

-- wlsunset

-- kitty

-- Firefox

-- Discord

-- Slack

-- KeepassXC

-- Thunderbird

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("dunst")
    hl.exec_cmd("systemctl --user start hypridle")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("wlsunset -l -59.3 -L -18.0")
    hl.exec_cmd("kitty -1", { workspace = "1 silent" })
    hl.exec_cmd("firefox", { workspace = "2 silent" })
    hl.exec_cmd("discord", { workspace = "3 silent" })
    hl.exec_cmd("slack", { workspace = "7 silent" })
    hl.exec_cmd("keepassxc", { workspace = "9 silent" })
    hl.exec_cmd("thunderbird", { workspace = "10 silent" })
end)
