-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ----------------------------------------------------- 

-- Key bindings

-- name: "Default"

-- ----------------------------------------------------- 

--TODO: Fix calculator float

local SCRIPTS = "~/.config/scripts"

-- SUPER KEY

local mainMod = "SUPER"

-- Applications

hl.bind(mainMod .. " + " .. "RETURN", hl.dsp.exec_cmd("kitty -1"))

-- Open the terminal

--bind = $mainMod, E, exec, nautilus # Open the filemanager not installef kek

--bind = $mainMod CTRL, C, exec, gnome-calculator # Open the calculator

-- Windows

hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())

-- Kill active window

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())

-- Set active window to fullscreen

hl.bind(mainMod .. " + " .. "T", hl.dsp.window.float())

-- Toggle active windows into floating mode

hl.bind(mainMod .. " + " .. "H", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "L", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "K", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "J", hl.dsp.focus({ direction = "down" }))

--bind = $mainMod, A, togglesplit # Toggle split

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

-- Move window with the mouse

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Resize window with the mouse

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "L", hl.dsp.window.resize({ x = 100, y = 0, relative = true }))

-- Increase window width with keyboard

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "H", hl.dsp.window.resize({ x = -100, y = 0, relative = true }))

-- Reduce window width with keyboard

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "J", hl.dsp.window.resize({ x = 0, y = 100, relative = true }))

-- Increase window height with keyboard

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "K", hl.dsp.window.resize({ x = 0, y = -100, relative = true }))

-- Reduce window height with keyboard

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "L", hl.dsp.workspace.move({ monitor = "r" }))

-- Move to monitor right

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "H", hl.dsp.workspace.move({ monitor = "l" }))

-- Move to monitor left

--bind = $mainMod, G, togglegroup # Toggle window group

--bind = $mainMod, S, swapsplit # Swapsplit

-- Actions

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.exec_cmd("grimblast copy area"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "D", hl.dsp.exec_cmd("grimblast save area - | satty --filename -"))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "Q", hl.dsp.exec_cmd("wlogout -b 2"))

-- Start wlogout

hl.bind(mainMod .. " + " .. "D", hl.dsp.exec_cmd("rofi -show drun -replace -i"))

-- Open application launcher

hl.bind(mainMod .. " + " .. "V", hl.dsp.exec_cmd("cliphist list | rofi -dmenu -replace -config ~/.config/rofi/config-cliphist.rasi | cliphist decode | wl-copy"))

-- Workspaces

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

-- Open workspace 1

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

-- Open workspace 2

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

-- Open workspace 3

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

-- Open workspace 4

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

-- Open workspace 5

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

-- Open workspace 6

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

-- Open workspace 7

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

-- Open workspace 8

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

-- Open workspace 9

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Open workspace 10

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

-- Move active window to workspace 1

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

-- Move active window to workspace 2

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

-- Move active window to workspace 3

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

-- Move active window to workspace 4

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

-- Move active window to workspace 5

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

-- Move active window to workspace 6

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

-- Move active window to workspace 7

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

-- Move active window to workspace 8

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

-- Move active window to workspace 9

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Move active window to workspace 10

hl.bind(mainMod .. " + " .. "Tab", hl.dsp.focus({ workspace = "m+1" }))

-- Open next workspace

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Tab", hl.dsp.focus({ workspace = "m-1" }))

-- Open previous workspace

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

-- Open next workspace

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Open previous workspace

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "down", hl.dsp.focus({ workspace = "empty" }))

-- Open the next empty workspace

-- Passthrough SUPER KEY to Virtual Machine

-- bind = $mainMod, P, submap, passthru # Passthrough SUPER key to virtual machine

-- submap = passthru

-- bind = SUPER, Escape, submap, reset # Get SUPER key back from virtual machine

-- submap = reset

-- Fn keys

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -q s +10%"))

-- Increase brightness by 10%

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -q s 10%-"))

-- Reduce brightness by 10%

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ +5%"))

-- Increase volume by 5%

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ -5%"))

-- Reduce volume by 5%

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"))

-- Toggle mute

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))

-- Audio play pause

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl pause"))

-- Audio pause

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))

-- Audio next

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))

-- Audio previous

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("pactl set-source-mute @DEFAULT_SOURCE@ toggle"))

-- Toggle microphone

hl.bind("XF86ScreenSaver", hl.dsp.exec_cmd("hyprlock"))

-- Open screenlock

hl.bind("code:238", hl.dsp.exec_cmd("brightnessctl -d smc::kbd_backlight s +10"))

hl.bind("code:237", hl.dsp.exec_cmd("brightnessctl -d smc::kbd_backlight s 10-"))
