-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ----------------------------------------------------- 

-- Keyboard Layout

-- https://wiki.hyprland.org/Configuring/Variables/#input

-- -----------------------------------------------------

hl.config({
    input = {
        kb_layout = "se",
        numlock_by_default = true,
        mouse_refocus = false,
        follow_mouse = 1,
        touchpad = {
            -- for desktop
            -- natural_scroll = false
            -- for laptop
            natural_scroll = true,
            middle_button_emulation = true,
            clickfinger_behavior = false,
            disable_while_typing = true,
            scroll_factor = 0.5,
            -- Touchpad scroll factor
        },
        sensitivity = 0,
        -- Pointer speed: -1.0 - 1.0, 0 means no modification.
    },
})

hl.gesture({
    ["fingers"] = 3,
    ["direction"] = "horizontal",
    ["action"] = "workspace",
})
