-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ----------------------------------------------------- 

-- Layouts

-- ----------------------------------------------------- 

hl.config({
    dwindle = {
        -- pseudotile = true
        preserve_split = true,
    },
})

hl.config({
    master = {
        -- Commented out due to compatibility reasons
        -- new_status = master
    },
})

hl.config({
    binds = {
        workspace_back_and_forth = true,
        allow_workspace_cycles = true,
        pass_mouse_when_bound = false,
    },
})
