-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local colors = require("colors")

-- ----------------------------------------------------- 

-- General window layout and colors

-- name: "Default"

-- ----------------------------------------------------- 

hl.config({
    general = {
        gaps_in = 10,
        gaps_out = 14,
        border_size = 3,
        layout = "dwindle",
        resize_on_border = true,
        col = {
            active_border = { colors = { colors.primary, "rgba(59595900)", colors.tertiary }, angle = 45 },
            inactive_border = "rgba(59595900)",
        },
    },
})
