-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Slack

hl.window_rule({
    name  = "slack-workspace",
    match = {
        class = "slack",
    },
    workspace = "7 silent",
})

-- Discord

hl.window_rule({
    name  = "discord-workspace",
    match = {
        class = "discord",
    },
    workspace = "3 silent",
})

-- Firefox smol video

hl.window_rule({
    name  = "firefox-pip",
    match = {
        title = "Picture-in-Picture",
    },
    size = { 900, 506 },
    move = { 1960, 61 },
    float = true,
    pin = true,
    opacity = "1.0 override 1.0 override",
})
