-- Generated by matugen - do not edit manually
return {
  base00 = '{{ base16.base00.dark.hex }}', -- background
  base01 = '{{ base16.base01.dark.hex }}', -- lighter bg (status bars, line number bg)
  base02 = '{{ base16.base02.dark.hex }}', -- selection bg
  base03 = '{{ base16.base03.dark.hex }}', -- comments
  base04 = '{{ base16.base04.dark.hex }}', -- dark fg (status bars)
  base05 = '{{ base16.base05.dark.hex }}', -- default fg
  base06 = '{{ base16.base06.dark.hex }}', -- light fg
  base07 = '{{ base16.base07.dark.hex }}', -- bright fg
  base08 = '{{ base16.base08.dark.hex }}', -- variables, diff deleted
  base09 = '{{ base16.base09.dark.hex }}', -- integers, booleans, constants
  base0A = '{{ base16.base0a.dark.hex }}', -- classes, search highlight
  base0B = '{{ base16.base0b.dark.hex }}', -- strings
  base0C = '{{ base16.base0c.dark.hex }}', -- regex, escape chars
  base0D = '{{ base16.base0d.dark.hex }}', -- functions, headings
  base0E = '{{ base16.base0e.dark.hex }}', -- keywords
  base0F = '{{ base16.base0f.dark.hex }}', -- deprecated
}
